modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="mte"
version="1.7.1"
displayName="Mekanism: Tinkerable Enhancements"
authors="Tau34"

description='''${mod_description}'''
[[dependencies.mte]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.mte]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.mte]]
modId="mekanismgenerators"
mandatory=true
versionRange="[10.4.0.14,)"
ordering="NONE"
side="BOTH"